{{- if .Values.worker.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netbox.fullname" . }}-worker
  labels:
    app.kubernetes.io/name: {{ include "netbox.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "netbox.chart" . }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "netbox.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: worker
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configuration.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "netbox.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-worker
          command:
            - /opt/netbox/venv/bin/python3
            - /opt/netbox/netbox/manage.py
            - rqworker
          image: "{{ .Values.image.repository }}:{{ include "netbox.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOME
              value: /tmp
          {{- if and (or .Values.redis.auth.existingSecret .Values.redis.enabled) (not .Values.redis.auth.password) }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.auth.existingSecret | default (include "netbox.redis.fullname" .) }}
                  key: {{ .Values.redis.auth.existingSecretPasswordKey | default "redis-password" }}
          {{- end }}
          {{- if .Values.existingDjangoSecret }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingDjangoSecret }}
                  key: {{ .Values.existingDjangoSecretKey }}
          {{- end }}
          {{- if (or .Values.postgresql.auth.existingSecret .Values.postgresql.enabled) }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                {{- if .Values.postgresql.auth.existingSecret }}
                  name: {{ .Values.postgresql.auth.existingSecret }}
                  key: {{ .Values.postgresql.auth.existingSecretKey | default "password" }}
                {{- else }}
                  name: {{ include "netbox.postgresql.fullname" . }}
                  key: password
                {{- end }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "netbox.fullname" . }}
            - secretRef:
                name: {{ include "netbox.fullname" . }}
          {{- with .Values.extraEnvFrom -}}
            {{ . | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          {{- if or .Values.extraConfiguration .Values.extraPlugins .Values.worker.extraVolumeMounts }}
          volumeMounts:
            {{- if .Values.extraConfiguration }}
            - name: netbox-extra-config
              mountPath: /etc/netbox/config/extra.py
              subPath: extra.py
            {{- end }}
            {{- if .Values.extraPlugins }}
            - name: netbox-extra-plugins
              mountPath: /etc/netbox/config/plugins.py
              subPath: plugins.py
            {{- end }}
          {{- if .Values.worker.extraVolumeMounts }}
            {{ toYaml .Values.worker.extraVolumeMounts | nindent 12 }}
          {{- end }}
          {{- end }}
    {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if or .Values.extraConfiguration .Values.extraPlugins .Values.worker.extraVolumes }}
      volumes:
      {{- if .Values.extraConfiguration }}
        - name: netbox-extra-config
          configMap:
            name: {{ .Chart.Name }}-extra
      {{- end }}
      {{- if .Values.extraPlugins }}
        - name: netbox-extra-plugins
          configMap:
            name: {{ .Chart.Name }}-plugins
      {{- end }}
      {{- if .Values.worker.extraVolumes }}
        {{ toYaml .Values.worker.extraVolumes | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
