{{ $secret := (lookup "v1" "Secret" .Release.Namespace (include "netbox.fullname" .)) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbox.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "netbox.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "netbox.chart" . }}
data:
{{- if and (.Values.postgresql.auth.password) (not .Values.postgresql.enabled) }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
{{- end }}
{{- if .Values.redis.auth.password }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | b64enc }}
{{- end }}
{{- if .Values.djangoSecret }}
  SECRET_KEY: {{ .Values.djangoSecret | b64enc }}
{{- else if and $secret $secret.data.SECRET_KEY }}
  SECRET_KEY: {{ $secret.data.SECRET_KEY }}
{{- else if not .Values.existingDjangoSecret }}
  SECRET_KEY: {{ randAlphaNum 50 | b64enc }}
{{- end }}

{{- if .Values.superuser.apiToken }}
  SUPERUSER_API_TOKEN: {{ .Values.superuser.apiToken | b64enc }}
{{- end }}
{{- if .Values.superuser.password }}
  SUPERUSER_PASSWORD: {{ .Values.superuser.password | b64enc }}
{{- end }}

{{- range $key, $value := .Values.extraSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
